/*
Cars owners API

This is a REST API of the Cars owners App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// OwnershipAddPostRequest struct for OwnershipAddPostRequest
type OwnershipAddPostRequest struct {
	Data []Ownership `json:"data"`
}

// NewOwnershipAddPostRequest instantiates a new OwnershipAddPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOwnershipAddPostRequest(data []Ownership) *OwnershipAddPostRequest {
	this := OwnershipAddPostRequest{}
	this.Data = data
	return &this
}

// NewOwnershipAddPostRequestWithDefaults instantiates a new OwnershipAddPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOwnershipAddPostRequestWithDefaults() *OwnershipAddPostRequest {
	this := OwnershipAddPostRequest{}
	return &this
}

// GetData returns the Data field value
func (o *OwnershipAddPostRequest) GetData() []Ownership {
	if o == nil {
		var ret []Ownership
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OwnershipAddPostRequest) GetDataOk() ([]Ownership, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *OwnershipAddPostRequest) SetData(v []Ownership) {
	o.Data = v
}

func (o OwnershipAddPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableOwnershipAddPostRequest struct {
	value *OwnershipAddPostRequest
	isSet bool
}

func (v NullableOwnershipAddPostRequest) Get() *OwnershipAddPostRequest {
	return v.value
}

func (v *NullableOwnershipAddPostRequest) Set(val *OwnershipAddPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnershipAddPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnershipAddPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnershipAddPostRequest(val *OwnershipAddPostRequest) *NullableOwnershipAddPostRequest {
	return &NullableOwnershipAddPostRequest{value: val, isSet: true}
}

func (v NullableOwnershipAddPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnershipAddPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
