/*
Cars owners API

This is a REST API of the Cars owners App.

API version: 0.0.1-beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// OwnershipAddPost201ResponseData struct for OwnershipAddPost201ResponseData
type OwnershipAddPost201ResponseData struct {
	Owners []Owner `json:"owners,omitempty"`
	Cars   []Car   `json:"cars,omitempty"`
}

// NewOwnershipAddPost201ResponseData instantiates a new OwnershipAddPost201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOwnershipAddPost201ResponseData() *OwnershipAddPost201ResponseData {
	this := OwnershipAddPost201ResponseData{}
	return &this
}

// NewOwnershipAddPost201ResponseDataWithDefaults instantiates a new OwnershipAddPost201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOwnershipAddPost201ResponseDataWithDefaults() *OwnershipAddPost201ResponseData {
	this := OwnershipAddPost201ResponseData{}
	return &this
}

// GetOwners returns the Owners field value if set, zero value otherwise.
func (o *OwnershipAddPost201ResponseData) GetOwners() []Owner {
	if o == nil || o.Owners == nil {
		var ret []Owner
		return ret
	}
	return o.Owners
}

// GetOwnersOk returns a tuple with the Owners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnershipAddPost201ResponseData) GetOwnersOk() ([]Owner, bool) {
	if o == nil || o.Owners == nil {
		return nil, false
	}
	return o.Owners, true
}

// HasOwners returns a boolean if a field has been set.
func (o *OwnershipAddPost201ResponseData) HasOwners() bool {
	if o != nil && o.Owners != nil {
		return true
	}

	return false
}

// SetOwners gets a reference to the given []Owner and assigns it to the Owners field.
func (o *OwnershipAddPost201ResponseData) SetOwners(v []Owner) {
	o.Owners = v
}

// GetCars returns the Cars field value if set, zero value otherwise.
func (o *OwnershipAddPost201ResponseData) GetCars() []Car {
	if o == nil || o.Cars == nil {
		var ret []Car
		return ret
	}
	return o.Cars
}

// GetCarsOk returns a tuple with the Cars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnershipAddPost201ResponseData) GetCarsOk() ([]Car, bool) {
	if o == nil || o.Cars == nil {
		return nil, false
	}
	return o.Cars, true
}

// HasCars returns a boolean if a field has been set.
func (o *OwnershipAddPost201ResponseData) HasCars() bool {
	if o != nil && o.Cars != nil {
		return true
	}

	return false
}

// SetCars gets a reference to the given []Car and assigns it to the Cars field.
func (o *OwnershipAddPost201ResponseData) SetCars(v []Car) {
	o.Cars = v
}

func (o OwnershipAddPost201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Owners != nil {
		toSerialize["owners"] = o.Owners
	}
	if o.Cars != nil {
		toSerialize["cars"] = o.Cars
	}
	return json.Marshal(toSerialize)
}

type NullableOwnershipAddPost201ResponseData struct {
	value *OwnershipAddPost201ResponseData
	isSet bool
}

func (v NullableOwnershipAddPost201ResponseData) Get() *OwnershipAddPost201ResponseData {
	return v.value
}

func (v *NullableOwnershipAddPost201ResponseData) Set(val *OwnershipAddPost201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnershipAddPost201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnershipAddPost201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnershipAddPost201ResponseData(val *OwnershipAddPost201ResponseData) *NullableOwnershipAddPost201ResponseData {
	return &NullableOwnershipAddPost201ResponseData{value: val, isSet: true}
}

func (v NullableOwnershipAddPost201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnershipAddPost201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
